// ./core/src/controller.rs
use crate::matcher::SearchExpr;
use crate::model::PlayerIntent;
use crate::store::LibraryStore;
use std::sync::Arc;
use tokio::sync::Mutex;

#[derive(Clone)]
pub struct PlayerController {
    pub store: Arc<Mutex<LibraryStore>>,
    pub explicit_queue: Vec<String>, // Tracks the user specifically enqueued
    pub dynamic_queue: Vec<String>,  // Tracks generated by the Smart Playlist
    pub history: Vec<String>,        // Tracks already played (for the "Previous" button)
    pub current_track: Option<String>,
    pub stop_after_current: bool,
    pub is_playing: bool,
}

impl PlayerController {
    pub fn new(store: Arc<Mutex<LibraryStore>>) -> Self {
        Self {
            store,
            explicit_queue: Vec::new(),
            dynamic_queue: Vec::new(),
            history: Vec::new(),
            current_track: None,
            stop_after_current: false,
            is_playing: false,
        }
    }

    /// Determines the next track, handling explicit queues, dynamic repopulation, and history.
    pub async fn determine_next_track(&mut self, fallback_query: &SearchExpr) -> Option<String> {
        if self.stop_after_current {
            self.stop_after_current = false;
            self.is_playing = false;
            return None;
        }

        // 1. Explicit Queue takes priority
        if !self.explicit_queue.is_empty() {
            let next_id = self.explicit_queue.remove(0);
            self.set_current_track(next_id.clone());
            return Some(next_id);
        }

        // 2. Replenish dynamic queue if empty
        if self.dynamic_queue.is_empty() {
            self.repopulate_dynamic_queue(fallback_query).await;
        }

        // 3. Play from dynamic queue
        if !self.dynamic_queue.is_empty() {
            let next_id = self.dynamic_queue.remove(0);
            self.set_current_track(next_id.clone());
            return Some(next_id);
        }

        self.is_playing = false;
        None
    }

    /// Pulls from history. Pushes the current track back to the explicit queue.
    pub async fn previous_track(&mut self) -> Option<String> {
        if let Some(prev_id) = self.history.pop() {
            // Push current track back onto the front of the explicit queue so we don't lose it
            if let Some(curr) = self.current_track.take() {
                self.explicit_queue.insert(0, curr);
            }
            self.current_track = Some(prev_id.clone());
            self.is_playing = true;
            return Some(prev_id);
        }
        None
    }

    /// Generates the next batch of tracks from the library based on the smart query
    async fn repopulate_dynamic_queue(&mut self, query: &SearchExpr) {
        let store = self.store.lock().await;
        let mut pool = store.filter(query, crate::model::SortPreset::Random);

        // Remove anything recently played to prevent repetition
        pool.retain(|t| {
            !self.history.contains(&t.id) && Some(&t.id) != self.current_track.as_ref()
        });

        // Take the top 20 randomized tracks for the dynamic queue
        self.dynamic_queue = pool.into_iter().take(20).map(|t| t.id.clone()).collect();
    }

    fn set_current_track(&mut self, id: String) {
        if let Some(prev) = self.current_track.take() {
            self.history.push(prev);
            // Cap history at 100 tracks to prevent memory leaks
            if self.history.len() > 100 {
                self.history.remove(0);
            }
        }
        self.current_track = Some(id);
        self.is_playing = true;
    }

    pub async fn dispatch(&mut self, intent: PlayerIntent) {
        match intent {
            PlayerIntent::Enqueue { id, next } => {
                if next {
                    self.explicit_queue.insert(0, id);
                } else {
                    self.explicit_queue.push(id);
                }
            }
            PlayerIntent::ClearQueue => {
                self.explicit_queue.clear();
                self.dynamic_queue.clear();
            }
            PlayerIntent::TogglePlayPause => {
                self.is_playing = !self.is_playing;
            }
            PlayerIntent::StopAfterCurrent => {
                self.stop_after_current = !self.stop_after_current;
            }
            _ => {} // Remaining intents
        }
    }
}
